### ISSUE TITLE
金额类型似乎需要修改成数字类型

### ISSUE THREAD

**Issue by id4alex** [QHh6eQ/tushare-pro-java-sdk#4]
TushareProService.moneyflowHsgt(new Request<MoneyflowHsgtEntity>() {}.allFields()).forEach(System.out::println)
当前版本会抛出double(float?)不能转换成String, 对entity类型做修改后正常

public class MoneyflowHsgtEntity implements MoneyflowHsgt {
    @Id
    @Column(name = "trade_date") protected LocalDate tradeDate;  // 交易日期
    @Column(name = "ggt_ss") protected Double ggtSs;  // 港股通（上海）
    @Column(name = "ggt_sz") protected Double ggtSz;  // 港股通（深圳）
    @Column(name = "hgt") protected Double hgt;  // 沪股通（百万元）
    @Column(name = "sgt") protected Double sgt;  // 深股通（百万元）
    @Column(name = "north_money") protected Double northMoney;  // 北向资金（百万元）
    @Column(name = "south_money") protected Double southMoney;  // 南向资金（百万元）
}

**Comment by QHh6eQ** [comment]
感谢反馈, 已在新版本中更正
